fix yaml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -90,9 +90,10 @@ error-codes:
     - unique_error_codes=$( echo "${error_codes}" | uniq -d -c )
     # Pipe to grep: count the number of lines with `E` (there will just be an empty line if there's duplicate error codes)
     - unique_error_codes_count=$( echo "${unique_error_codes}" | grep E -c)
-    - if [[ ${unique_error_codes_count} == 0 ]]; then
-    - echo -e "Error codes are unique as they should be";
-    - else echo -e "Duplicate error codes found!"; echo "${unique_error_codes}"; exit 1; fi
+    - |
+      if [[ ${unique_error_codes_count} == 0 ]]; then
+      echo -e "Error codes are unique as they should be";
+      else echo -e "Duplicate error codes found!"; echo "${unique_error_codes}"; exit 1; fi
 
 ### end of stage: code-quality
 
