add more regression tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -116,19 +116,29 @@ regression-tests:
   stage: build-and-test
   before_script:
     - |
+      test_cmds="test-data/tests.txt"
+      IFS=$'\n' read -d '' -r -a cmd_list < $test_cmds
       TXT_RED="\e[31m";
       TXT_YELLOW="\e[33m";
       TXT_BRIGHT_YELLOW="\e[93m";
       TXT_BRIGHT_CYAN="\e[96m";
       TXT_CLEAR="\e[0m";
+      ig="egrep -i" # Case insensitive egrep
       all_test_passed="echo all test passed!";
     - cargo build
     - test_1="cargo run -- ./test-data/readout.superpage.1.raw check all its -v2"
     - pattern_1="Data Format.*2|((INFO -).*((EOF)|(Exit Successful))*)"
     - test_2="cargo run -- ./test-data/readout.superpage.1.raw check sanity its"
     - pattern_2="Data Format.*2";
-    - |
-      test_3="cargo run -- ./test-data/readout.superpage.1.raw view rdh"
+    - | # Test on 10_rdh.raw
+      test_3a="cargo run -- ./test-data/10_rdh.raw check sanity"
+      pattern_3a="RDHs.*Version.*7"
+      match_3a="${ig} '${pattern_3a}'"
+      cond_3a="-eq 1"
+      pattern_3b="Total.*RDHs.*10"
+      match_3b="$ig '{pattern_3b}'"
+      cond_3a="-eq 1"
+
 
   script:
     - |
@@ -143,6 +153,21 @@ regression-tests:
       test_out=$(eval "$test_2" 2>&1);
       pattern_2_match=$(echo "$test_out" | egrep "$pattern_2" | wc -l)
     - if [[ "$pattern_2_match" -ne 1 ]]; then echo -e "${TXT_RED}Test failed${TXT_CLEAR} $test_2"; all_test_passed="exit 1"; fi;
+    - |
+      echo -e "running test ${TXT_BRIGHT_YELLOW}$test_2${TXT_CLEAR}";
+      echo -e "1 line should match ${TXT_BRIGHT_CYAN}$pattern_3a";
+      test_out=$(eval "$test_3a" 2>&1);
+      pattern_3a_match=$(echo "$test_out" | $match_3a | wc -l)
+    - if [[ "$pattern_3a_match" $"cond_3a" ]]; then echo -e "${TXT_RED}Test failed${TXT_CLEAR} $test_3a"; all_test_passed="exit 1"; fi;
+    - |
+      for (( i=0; i<${#cmd_list[@]}; i+=3 )); do test=${cmd_list[i]}; pattern=${cmd_list[i+1]}; cond=${cmd_list[i+2]};
+      echo "Executing commands: $cmd1, $cmd2, $cmd3";
+      echo -e "running test ${TXT_BRIGHT_YELLOW}$test${TXT_CLEAR}";
+      echo -e "Condition: ${TXT_BRIGHT_YELLOW}${cond}${TXT_CLEAR} for ${TXT_BRIGHT_CYAN}$pattern";
+      test_out=$(eval $test 2>&1);
+      matches=$(echo $"test_out" | egrep -i '${pattern}' | wc -l)
+      if [[ "$matches" "$cond" ]]; then echo -e "${TXT_RED}Test failed${TXT_CLEAR} $test"; all_test_passed="exit 1"; fi;
+      done
     - eval "$all_test_passed"
 
 ## For release build
