simplify

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -81,15 +81,18 @@ audit:
 error-codes:
   stage: code-quality
   script:
-   # find: Find all files in `src/` and give them to `sed`.
-   # sed: Read all file content until the string "cfg(test)" (delimits design and test code)
-   # Pipe to grep: Match pattern and output exact match content (error codes)
-   # Pipe to uniq: Output all duplicate lines
-   # Pipe to wc : count the number of lines
-    - duplicates=$( find src/ -type f -exec sed -e "/cfg(test)/,\$d" {} \; | grep -Po "E[0-9]{2,4}" | uniq -d -c | wc -l )
-    - if [[ ${duplicates} == 0 ]]; then
+    # find: Find all files in `src/` and give them to `sed`.
+    # sed: Read all file content until the string "cfg(test)" (delimits design and test code)
+    - design_code=$( find src/ -type f -exec sed -e "/cfg(test)/,\$d" {} \; )
+    # Pipe to grep: Match pattern and output exact match content (error codes)
+    - error_codes$( echo "${design_code}" | grep -Po "E[0-9]{2,4}" )
+    # Pipe to uniq: Output all duplicate lines
+    - unique_error_codes=$( echo "${error_codes}" | uniq -d -c )
+    # Pipe to wc: count the number of lines with unique error codes
+    - unique_error_codes_count=$( echo "${unique_error_codes}" | wc -l )
+    - if [[ ${unique_error_codes_count} == 0 ]]; then
     - echo -e "Error codes are unique as they should be";
-    - else echo -e "Duplicate error codes found!"; exit 1; fi
+    - else echo -e "Duplicate error codes found!"; echo "${unique_error_codes}"; exit 1; fi
 
 ### end of stage: code-quality
 
